name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - scala-version: 2.12.11
            spark-version: 3.0.0
          - scala-version: 2.12.11
            spark-version: 3.1.2
          - scala-version: 2.12.11
            spark-version: 3.2.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Prepare python env
      env:
        SPARK_VERSION: ${{ matrix.spark-version }}
      run: >-
        python -m
        pip install
        pytest==8.2.1
        pyspark==$SPARK_VERSION 
        python/
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests
      env:
        SCALA_VERSION: ${{ matrix.scala-version }}
        SPARK_VERSION: ${{ matrix.spark-version }}
      run: ./gradlew clean build pythonTest -PscalaVersion=$SCALA_VERSION -PsparkVersion=$SPARK_VERSION
